name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  # For Remote Caching
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check if merged to main
        id: environment
        run: |
          if [[ ${{ github.event.pull_request.merged == true }} ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT 
          else
            echo "environment=preview" >> $GITHUB_OUTPUT
          fi

      - name: Print environment
        run: echo ${{ steps.environment.outputs.environment }}

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Globally install Turborepo
        run: pnpm install -g turbo@2.0.9

      - name: Build
        run: |
          # Builds the dependencies of the docs target
          # https://turbo.build/repo/docs/reference/run#microsyntaxes-for-filtering
          # We need to do this since  `vc build` does not currently
          # follow the package or task graph (like Turborepo can).
          turbo build --filter=docs^...
          # Pull environment info
          vercel pull --yes --environment=${{ steps.environment.outputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --environment=${{ steps.environment.outputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: vc deploy --prebuilt --prod=${{ steps.environment.outputs.environment == 'production' }} --token=${{ secrets.VERCEL_TOKEN }}
